name: Test e2e
env:
  PLUGIN_NAME: obsidian-to-anki-plugin
  NODE_V: "18.x"
on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [master]
  repository_dispatch:
    types: [ok-to-test-command]
permissions: {}
# TODO:
# permissions:
#   checks: write
#   pull-requests: write
jobs:
  checkout-trusted:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Branch based PR checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Use Node.js ${{ env.NODE_V }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_V }}
      - run: "npm install obsidian \nnpm ci\n"
      - run: npm run build --if-present
      - name: Run Tests
        run: |
          # npm run test
          sudo npm run test-wdio
          sudo npm run test-py
      - name: Set output perms
        if: always()
        run: |
          echo "Current user for this action is - $USER $(id -u)"
          sudo chown -R "$(whoami)" tests/test_config
          sudo chown -R "$(whoami)" tests/test_vault

          ls -alh
          ls -alh tests/test_config/
          ls -alh "tests/test_config/.local/share/Anki2/User 1/"
      - name: Package
        if: always()
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css README.md ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
      - name: Publish Test Results in Comment
        uses: EnricoMi/publish-unit-test-result-action@34d7c956a59aed1bfebf31df77b8de55db9bbaaf # v2.21.0
        # if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository && always()
        if: always()
        with:
          report_individual_runs: true
          report_suite_logs: "any"
          deduplicate_classes_by_file_name: true
          comment_title: "🛠 Test Results"
          files: |
            logs/test-reports/**/*.xml
      # - name: Publish Test Results
      #   uses: dorny/test-reporter@v1
      #   if: success() || failure()
      #   with:
      #     name: JUnit Reprot
      #     path: logs/test-reports/wdio.xml
      #     reporter: jest-junit
      - uses: actions/setup-node@v6
        with:
          node-version: 16
      - uses: iterative/setup-cml@f12ea7685438c1fc438d50f77519b3860cf5fa98 # v2.0.1
        if: always()
      - name: Publish Screenshots - Find Comment
        if: always()
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "# 📷 Screenshots of tests:"
          direction: last
          comment-author: "github-actions[bot]"
      - name: Publish Screenshots - build comment
        if: always()
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT: ${{ github.event_name }}
          REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
          PULL_REQUEST_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          WORKFLOW_RUN_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
        shell: bash
        run: |
          bash << 'EOF'
          . templates/screenshot.sh
          EOF
      - name: Publish Screehnshots - Update or Create Comment
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository && always()
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body-file: comment.md
          edit-mode: replace
          issue-number: ${{ github.event.number }}
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.PLUGIN_NAME }}
          path: |
            ${{ env.PLUGIN_NAME }}.zip
            logs/*
            tests/test_config/logs/*
            tests/test_config/*.png
            # tests/test_config/.xsession-errors
      - name: Upload build artifacts for failed builds
        if: failure()
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.PLUGIN_NAME }}-fail
          path: |
            tests/test_config
            tests/test_vault
  checkout-signed:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      checks: write
    if: |
      github.event_name == 'repository_dispatch' &&
      github.event.client_payload.slash_command.args.named.sha != '' &&
      contains(
        github.event.client_payload.pull_request.head.sha,
        github.event.client_payload.slash_command.args.named.sha
      )
    steps:
      # Check out merge commit
      - name: Fork based /ok-to-test checkout
        uses: actions/checkout@v5
        with:
          ref: "refs/pull/${{ github.event.client_payload.pull_request.number }}/merge"
          persist-credentials: false
          # Test:
          #   if: always()
          #   needs: [checkout-trusted, checkout-signed]
          #   runs-on: ubuntu-latest
      # - name: Trusted Checkout
      #   if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
      #   uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_V }}
        #   strategy:
        #     matrix:
        #       node-version: [18.x]

        # steps:
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_V }}
      - run: "npm install obsidian \nnpm ci\n"
      - run: npm run build --if-present
      - name: Run Tests
        # - run: npm test

        run: |
          # npm run test
          sudo npm run test-wdio
          sudo npm run test-py
      - name: Set output perms
        if: always()
        run: |
          echo "Current user for this action is - $USER $(id -u)"
          sudo chown -R "$(whoami)" tests/test_config
          sudo chown -R "$(whoami)" tests/test_vault

          ls -alh
          ls -alh tests/test_config/
          ls -alh "tests/test_config/.local/share/Anki2/User 1/"
      - name: Package
        if: always()
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css README.md ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
      - name: Publish Test Results in Comment
        uses: EnricoMi/publish-unit-test-result-action@34d7c956a59aed1bfebf31df77b8de55db9bbaaf # v2.21.0
        if: always()
        with:
          report_individual_runs: true
          report_suite_logs: "any"
          deduplicate_classes_by_file_name: true
          comment_title: "🛠 Test Results"
          commit: ${{ github.event.client_payload.pull_request.head.sha }}
          files: |
            logs/test-reports/**/*.xml
      # - name: Publish Test Results
      #   uses: dorny/test-reporter@v1
      #   if: success() || failure()
      #   with:
      #     name: JUnit Reprot
      #     path: logs/test-reports/wdio.xml
      #     reporter: jest-junit
      - uses: iterative/setup-cml@f12ea7685438c1fc438d50f77519b3860cf5fa98 # v2.0.1
        if: always()
      - name: Publish Screenshots - Find Comment
        if: always()
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        id: fc
        with:
          issue-number: ${{ github.event.client_payload.pull_request.number }}
          body-includes: "# 📷 Screenshots of tests:"
          direction: last
          comment-author: "github-actions[bot]"
      - name: Publish Screenshots - build comment
        if: always()
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT: ${{ github.event_name }}
          REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
          PULL_REQUEST_HEAD_SHA: ${{ github.event.client_payload.pull_request.head.sha }}
          WORKFLOW_RUN_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
        shell: bash
        run: |
          bash << 'EOF'
          . templates/screenshot.sh
          EOF
      - name: Publish Screehnshots - Update or Create Comment
        if: always()
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body-file: comment.md
          edit-mode: replace
          issue-number: ${{ github.event.client_payload.pull_request.number }}
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.PLUGIN_NAME }}
          path: |
            ${{ env.PLUGIN_NAME }}.zip
            logs/*
            tests/test_config/logs/*
            tests/test_config/*.png
            # tests/test_config/.xsession-errors
      - name: Upload build artifacts for failed builds
        if: failure()
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.PLUGIN_NAME }}-fail
          path: |
            tests/test_config
            tests/test_vault
          # MapjobStatus:
          #   needs: [Test]
          #   runs-on: ubuntu-latest
          #   if: |
          #     github.event_name == 'repository_dispatch' &&
          #     github.event.client_payload.slash_command.args.named.sha != '' &&
          #     contains(
          #       github.event.client_payload.pull_request.head.sha,
          #       github.event.client_payload.slash_command.args.named.sha
          #     )
      - uses: actions/github-script@v8
        #   steps:

        id: update-check-run
        if: ${{ always() }}
        env:
          number: ${{ github.event.client_payload.pull_request.number }}
          job: ${{ github.job }}
          # Conveniently, job.status maps to https://developer.github.com/v3/checks/runs/#update-a-check-run
          conclusion: ${{ job.status }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pull } = await github.rest.pulls.get({
              ...context.repo,
              pull_number: process.env.number
            });
            const ref = pull.head.sha;
            const { data: checks } = await github.rest.checks.listForRef({
              ...context.repo,
              ref
            });
            const check = checks.check_runs.filter(c => c.name === process.env.job);
            if( check ) {
              const { data: result } = await github.rest.checks.update({
                ...context.repo,
                check_run_id: check[0].id,
                status: 'completed',
                conclusion: process.env.conclusion
              });
              return result;
            }
